### ISSUE TITLE
Latest -> Any only has one result on MP4

### ISSUE THREAD

**Issue by LinUwUxCat** [GreepTheSheep/openplanet-maniaexchange-menu#24]
Going into the Latest tab and selecting "Any" as environment only returns the map Uganda by Line, which was made in 2020. 
![image](https://github.com/GreepTheSheep/openplanet-maniaexchange-menu/assets/46047705/4a726c5c-812c-4116-b5ba-303eb75e78d6)

**Comment by Fort-TM** [comment]
This is caused by passing environments="0" to the TMX API, [which is used for custom envis](https://api2.mania.exchange/Enum/Index/2). #29 fixes this by changing the environment name with ID 0 to "Custom", and adding another one for "Any", only passing the environments parameter to the API if anything but Any is selected
